// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.3
// source: polar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaseVerdict int32

const (
	CaseVerdict_ACCEPTED              CaseVerdict = 0
	CaseVerdict_WRONG_ANSWER          CaseVerdict = 1
	CaseVerdict_INTERNAL_ERROR        CaseVerdict = 2
	CaseVerdict_TIME_LIMIT_EXCEEDED   CaseVerdict = 3
	CaseVerdict_MEMORY_LIMIT_EXCEEDED CaseVerdict = 4
	CaseVerdict_OUTPUT_LIMIT_EXCEEDED CaseVerdict = 5
	CaseVerdict_RUNTIME_ERROR         CaseVerdict = 6
)

// Enum value maps for CaseVerdict.
var (
	CaseVerdict_name = map[int32]string{
		0: "ACCEPTED",
		1: "WRONG_ANSWER",
		2: "INTERNAL_ERROR",
		3: "TIME_LIMIT_EXCEEDED",
		4: "MEMORY_LIMIT_EXCEEDED",
		5: "OUTPUT_LIMIT_EXCEEDED",
		6: "RUNTIME_ERROR",
	}
	CaseVerdict_value = map[string]int32{
		"ACCEPTED":              0,
		"WRONG_ANSWER":          1,
		"INTERNAL_ERROR":        2,
		"TIME_LIMIT_EXCEEDED":   3,
		"MEMORY_LIMIT_EXCEEDED": 4,
		"OUTPUT_LIMIT_EXCEEDED": 5,
		"RUNTIME_ERROR":         6,
	}
)

func (x CaseVerdict) Enum() *CaseVerdict {
	p := new(CaseVerdict)
	*p = x
	return p
}

func (x CaseVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_polar_proto_enumTypes[0].Descriptor()
}

func (CaseVerdict) Type() protoreflect.EnumType {
	return &file_polar_proto_enumTypes[0]
}

func (x CaseVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseVerdict.Descriptor instead.
func (CaseVerdict) EnumDescriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{0}
}

type FinalVerdict int32

const (
	FinalVerdict_NORMAL               FinalVerdict = 0
	FinalVerdict_SHORT_CIRCUIT        FinalVerdict = 1
	FinalVerdict_REJECTED             FinalVerdict = 2
	FinalVerdict_CANCELLED            FinalVerdict = 3
	FinalVerdict_COMPILATION_ERROR    FinalVerdict = 4
	FinalVerdict_INITIALIZATION_ERROR FinalVerdict = 5
)

// Enum value maps for FinalVerdict.
var (
	FinalVerdict_name = map[int32]string{
		0: "NORMAL",
		1: "SHORT_CIRCUIT",
		2: "REJECTED",
		3: "CANCELLED",
		4: "COMPILATION_ERROR",
		5: "INITIALIZATION_ERROR",
	}
	FinalVerdict_value = map[string]int32{
		"NORMAL":               0,
		"SHORT_CIRCUIT":        1,
		"REJECTED":             2,
		"CANCELLED":            3,
		"COMPILATION_ERROR":    4,
		"INITIALIZATION_ERROR": 5,
	}
)

func (x FinalVerdict) Enum() *FinalVerdict {
	p := new(FinalVerdict)
	*p = x
	return p
}

func (x FinalVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_polar_proto_enumTypes[1].Descriptor()
}

func (FinalVerdict) Type() protoreflect.EnumType {
	return &file_polar_proto_enumTypes[1]
}

func (x FinalVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalVerdict.Descriptor instead.
func (FinalVerdict) EnumDescriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{1}
}

type Submission_Constraints_Flag int32

const (
	Submission_Constraints_NONE          Submission_Constraints_Flag = 0
	Submission_Constraints_INTERACTIVE   Submission_Constraints_Flag = 1
	Submission_Constraints_SHORT_CIRCUIT Submission_Constraints_Flag = 2
)

// Enum value maps for Submission_Constraints_Flag.
var (
	Submission_Constraints_Flag_name = map[int32]string{
		0: "NONE",
		1: "INTERACTIVE",
		2: "SHORT_CIRCUIT",
	}
	Submission_Constraints_Flag_value = map[string]int32{
		"NONE":          0,
		"INTERACTIVE":   1,
		"SHORT_CIRCUIT": 2,
	}
)

func (x Submission_Constraints_Flag) Enum() *Submission_Constraints_Flag {
	p := new(Submission_Constraints_Flag)
	*p = x
	return p
}

func (x Submission_Constraints_Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Submission_Constraints_Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_polar_proto_enumTypes[2].Descriptor()
}

func (Submission_Constraints_Flag) Type() protoreflect.EnumType {
	return &file_polar_proto_enumTypes[2]
}

func (x Submission_Constraints_Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Submission_Constraints_Flag.Descriptor instead.
func (Submission_Constraints_Flag) EnumDescriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{5, 0, 0}
}

type Request_Type int32

const (
	Request_REGISTER           Request_Type = 0
	Request_CONSUME            Request_Type = 1
	Request_UPDATE_SYSTEM_LOAD Request_Type = 2
)

// Enum value maps for Request_Type.
var (
	Request_Type_name = map[int32]string{
		0: "REGISTER",
		1: "CONSUME",
		2: "UPDATE_SYSTEM_LOAD",
	}
	Request_Type_value = map[string]int32{
		"REGISTER":           0,
		"CONSUME":            1,
		"UPDATE_SYSTEM_LOAD": 2,
	}
)

func (x Request_Type) Enum() *Request_Type {
	p := new(Request_Type)
	*p = x
	return p
}

func (x Request_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Request_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_polar_proto_enumTypes[3].Descriptor()
}

func (Request_Type) Type() protoreflect.EnumType {
	return &file_polar_proto_enumTypes[3]
}

func (x Request_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Request_Type.Descriptor instead.
func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{6, 0}
}

type CaseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseId        uint32      `protobuf:"varint,1,opt,name=caseId,proto3" json:"caseId,omitempty"`
	ExecutionTime uint32      `protobuf:"varint,2,opt,name=executionTime,proto3" json:"executionTime,omitempty"`
	Memory        uint32      `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Feedback      string      `protobuf:"bytes,4,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Verdict       CaseVerdict `protobuf:"varint,5,opt,name=verdict,proto3,enum=polar.CaseVerdict" json:"verdict,omitempty"`
}

func (x *CaseResult) Reset() {
	*x = CaseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseResult) ProtoMessage() {}

func (x *CaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseResult.ProtoReflect.Descriptor instead.
func (*CaseResult) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{0}
}

func (x *CaseResult) GetCaseId() uint32 {
	if x != nil {
		return x.CaseId
	}
	return 0
}

func (x *CaseResult) GetExecutionTime() uint32 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

func (x *CaseResult) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *CaseResult) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *CaseResult) GetVerdict() CaseVerdict {
	if x != nil {
		return x.Verdict
	}
	return CaseVerdict_ACCEPTED
}

type FinalResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompilerOutput   string       `protobuf:"bytes,1,opt,name=compilerOutput,proto3" json:"compilerOutput,omitempty"`
	LastNonAcVerdict CaseVerdict  `protobuf:"varint,2,opt,name=lastNonAcVerdict,proto3,enum=polar.CaseVerdict" json:"lastNonAcVerdict,omitempty"`
	Verdict          FinalVerdict `protobuf:"varint,3,opt,name=verdict,proto3,enum=polar.FinalVerdict" json:"verdict,omitempty"`
}

func (x *FinalResult) Reset() {
	*x = FinalResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalResult) ProtoMessage() {}

func (x *FinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalResult.ProtoReflect.Descriptor instead.
func (*FinalResult) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{1}
}

func (x *FinalResult) GetCompilerOutput() string {
	if x != nil {
		return x.CompilerOutput
	}
	return ""
}

func (x *FinalResult) GetLastNonAcVerdict() CaseVerdict {
	if x != nil {
		return x.LastNonAcVerdict
	}
	return CaseVerdict_ACCEPTED
}

func (x *FinalResult) GetVerdict() FinalVerdict {
	if x != nil {
		return x.Verdict
	}
	return FinalVerdict_NORMAL
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Result_Case
	//	*Result_Final
	//	*Result_None
	Data isResult_Data `protobuf_oneof:"data"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{2}
}

func (m *Result) GetData() isResult_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Result) GetCase() *CaseResult {
	if x, ok := x.GetData().(*Result_Case); ok {
		return x.Case
	}
	return nil
}

func (x *Result) GetFinal() *FinalResult {
	if x, ok := x.GetData().(*Result_Final); ok {
		return x.Final
	}
	return nil
}

func (x *Result) GetNone() *emptypb.Empty {
	if x, ok := x.GetData().(*Result_None); ok {
		return x.None
	}
	return nil
}

type isResult_Data interface {
	isResult_Data()
}

type Result_Case struct {
	Case *CaseResult `protobuf:"bytes,1,opt,name=case,proto3,oneof"`
}

type Result_Final struct {
	Final *FinalResult `protobuf:"bytes,2,opt,name=final,proto3,oneof"`
}

type Result_None struct {
	None *emptypb.Empty `protobuf:"bytes,3,opt,name=none,proto3,oneof"`
}

func (*Result_Case) isResult_Data() {}

func (*Result_Final) isResult_Data() {}

func (*Result_None) isResult_Data() {}

type Judge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Parallelism uint32           `protobuf:"varint,3,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	Runtimes    []*Judge_Runtime `protobuf:"bytes,4,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
}

func (x *Judge) Reset() {
	*x = Judge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Judge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Judge) ProtoMessage() {}

func (x *Judge) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Judge.ProtoReflect.Descriptor instead.
func (*Judge) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{3}
}

func (x *Judge) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Judge) GetParallelism() uint32 {
	if x != nil {
		return x.Parallelism
	}
	return 0
}

func (x *Judge) GetRuntimes() []*Judge_Runtime {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type RuntimeDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompileCmd  string `protobuf:"bytes,2,opt,name=compileCmd,proto3" json:"compileCmd,omitempty"`
	CompileArgs string `protobuf:"bytes,3,opt,name=compileArgs,proto3" json:"compileArgs,omitempty"`
	ExecCmd     string `protobuf:"bytes,4,opt,name=execCmd,proto3" json:"execCmd,omitempty"`
	VersionCmd  string `protobuf:"bytes,5,opt,name=versionCmd,proto3" json:"versionCmd,omitempty"`
	Extension   string `protobuf:"bytes,6,opt,name=extension,proto3" json:"extension,omitempty"`
}

func (x *RuntimeDefinition) Reset() {
	*x = RuntimeDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeDefinition) ProtoMessage() {}

func (x *RuntimeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeDefinition.ProtoReflect.Descriptor instead.
func (*RuntimeDefinition) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeDefinition) GetCompileCmd() string {
	if x != nil {
		return x.CompileCmd
	}
	return ""
}

func (x *RuntimeDefinition) GetCompileArgs() string {
	if x != nil {
		return x.CompileArgs
	}
	return ""
}

func (x *RuntimeDefinition) GetExecCmd() string {
	if x != nil {
		return x.ExecCmd
	}
	return ""
}

func (x *RuntimeDefinition) GetVersionCmd() string {
	if x != nil {
		return x.VersionCmd
	}
	return ""
}

func (x *RuntimeDefinition) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type Submission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceCode  string                  `protobuf:"bytes,2,opt,name=sourceCode,proto3" json:"sourceCode,omitempty"`
	RuntimeId   string                  `protobuf:"bytes,3,opt,name=runtimeId,proto3" json:"runtimeId,omitempty"`
	ProblemCode string                  `protobuf:"bytes,4,opt,name=problemCode,proto3" json:"problemCode,omitempty"`
	TestCount   uint32                  `protobuf:"varint,5,opt,name=testCount,proto3" json:"testCount,omitempty"`
	Constraints *Submission_Constraints `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	AuthorId    uint32                  `protobuf:"varint,7,opt,name=authorId,proto3" json:"authorId,omitempty"`
}

func (x *Submission) Reset() {
	*x = Submission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Submission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission) ProtoMessage() {}

func (x *Submission) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission.ProtoReflect.Descriptor instead.
func (*Submission) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{5}
}

func (x *Submission) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Submission) GetSourceCode() string {
	if x != nil {
		return x.SourceCode
	}
	return ""
}

func (x *Submission) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

func (x *Submission) GetProblemCode() string {
	if x != nil {
		return x.ProblemCode
	}
	return ""
}

func (x *Submission) GetTestCount() uint32 {
	if x != nil {
		return x.TestCount
	}
	return 0
}

func (x *Submission) GetConstraints() *Submission_Constraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Submission) GetAuthorId() uint32 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Request_Type `protobuf:"varint,1,opt,name=type,proto3,enum=polar.Request_Type" json:"type,omitempty"`
	Data *anypb.Any   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{6}
}

func (x *Request) GetType() Request_Type {
	if x != nil {
		return x.Type
	}
	return Request_REGISTER
}

func (x *Request) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type HandshakeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runtimes []*RuntimeDefinition `protobuf:"bytes,1,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
}

func (x *HandshakeData) Reset() {
	*x = HandshakeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeData) ProtoMessage() {}

func (x *HandshakeData) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeData.ProtoReflect.Descriptor instead.
func (*HandshakeData) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{7}
}

func (x *HandshakeData) GetRuntimes() []*RuntimeDefinition {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*Response_HandshakeData
	//	*Response_Submission
	//	*Response_X
	Data isResponse_Data `protobuf_oneof:"data"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{8}
}

func (m *Response) GetData() isResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Response) GetHandshakeData() *HandshakeData {
	if x, ok := x.GetData().(*Response_HandshakeData); ok {
		return x.HandshakeData
	}
	return nil
}

func (x *Response) GetSubmission() *Submission {
	if x, ok := x.GetData().(*Response_Submission); ok {
		return x.Submission
	}
	return nil
}

func (x *Response) GetX() *emptypb.Empty {
	if x, ok := x.GetData().(*Response_X); ok {
		return x.X
	}
	return nil
}

type isResponse_Data interface {
	isResponse_Data()
}

type Response_HandshakeData struct {
	HandshakeData *HandshakeData `protobuf:"bytes,1,opt,name=handshakeData,proto3,oneof"`
}

type Response_Submission struct {
	Submission *Submission `protobuf:"bytes,2,opt,name=submission,proto3,oneof"`
}

type Response_X struct {
	X *emptypb.Empty `protobuf:"bytes,3,opt,name=_,proto3,oneof"`
}

func (*Response_HandshakeData) isResponse_Data() {}

func (*Response_Submission) isResponse_Data() {}

func (*Response_X) isResponse_Data() {}

type Judge_Runtime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Judge_Runtime) Reset() {
	*x = Judge_Runtime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Judge_Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Judge_Runtime) ProtoMessage() {}

func (x *Judge_Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Judge_Runtime.ProtoReflect.Descriptor instead.
func (*Judge_Runtime) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Judge_Runtime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Judge_Runtime) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Submission_Constraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags       uint32  `protobuf:"varint,1,opt,name=flags,proto3" json:"flags,omitempty"`
	TimeLimit   float32 `protobuf:"fixed32,2,opt,name=timeLimit,proto3" json:"timeLimit,omitempty"`
	MemoryLimit uint32  `protobuf:"varint,3,opt,name=memoryLimit,proto3" json:"memoryLimit,omitempty"`
	OutputLimit uint32  `protobuf:"varint,4,opt,name=outputLimit,proto3" json:"outputLimit,omitempty"`
}

func (x *Submission_Constraints) Reset() {
	*x = Submission_Constraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polar_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Submission_Constraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Submission_Constraints) ProtoMessage() {}

func (x *Submission_Constraints) ProtoReflect() protoreflect.Message {
	mi := &file_polar_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Submission_Constraints.ProtoReflect.Descriptor instead.
func (*Submission_Constraints) Descriptor() ([]byte, []int) {
	return file_polar_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Submission_Constraints) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Submission_Constraints) GetTimeLimit() float32 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *Submission_Constraints) GetMemoryLimit() uint32 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *Submission_Constraints) GetOutputLimit() uint32 {
	if x != nil {
		return x.OutputLimit
	}
	return 0
}

var File_polar_proto protoreflect.FileDescriptor

var file_polar_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a,
	0x0a, 0x43, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x61, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x2c, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69,
	0x63, 0x74, 0x52, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x0b,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x3e, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x6f, 0x6e, 0x41, 0x63,
	0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63,
	0x74, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x6f, 0x6e, 0x41, 0x63, 0x56, 0x65, 0x72, 0x64,
	0x69, 0x63, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x52, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69,
	0x63, 0x74, 0x22, 0x93, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a,
	0x04, 0x63, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x6f,
	0x6c, 0x61, 0x72, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x63, 0x61, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x05, 0x66, 0x69, 0x6e,
	0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x6f, 0x6e, 0x65,
	0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xaa, 0x01, 0x0a, 0x05, 0x4a, 0x75, 0x64,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x69, 0x73, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x69, 0x73, 0x6d, 0x12, 0x30,
	0x0a, 0x08, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x2e, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x1a, 0x33, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xbd, 0x01, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x43, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63,
	0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x78, 0x65, 0x63, 0x43, 0x6d, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x43, 0x6d, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6d, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb5, 0x03, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49, 0x64, 0x1a,
	0xbb, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x66, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x34, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x48,
	0x4f, 0x52, 0x54, 0x5f, 0x43, 0x49, 0x52, 0x43, 0x55, 0x49, 0x54, 0x10, 0x02, 0x22, 0x97, 0x01,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d, 0x45, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d,
	0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x10, 0x02, 0x22, 0x45, 0x0a, 0x0d, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x6f, 0x6c,
	0x61, 0x72, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x22, 0xac,
	0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x68,
	0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0d, 0x68, 0x61, 0x6e, 0x64,
	0x73, 0x68, 0x61, 0x6b, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x33, 0x0a, 0x0a, 0x73, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25,
	0x0a, 0x01, 0x5f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x48, 0x00, 0x52, 0x00, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0xa3, 0x01,
	0x0a, 0x0b, 0x43, 0x61, 0x73, 0x65, 0x56, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x57,
	0x52, 0x4f, 0x4e, 0x47, 0x5f, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x02, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f,
	0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45,
	0x4d, 0x4f, 0x52, 0x59, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x45,
	0x44, 0x45, 0x44, 0x10, 0x04, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x5f,
	0x4c, 0x49, 0x4d, 0x49, 0x54, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x05,
	0x12, 0x11, 0x0a, 0x0d, 0x52, 0x55, 0x4e, 0x54, 0x49, 0x4d, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x06, 0x2a, 0x7b, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x64,
	0x69, 0x63, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x53, 0x48, 0x4f, 0x52, 0x54, 0x5f, 0x43, 0x49, 0x52, 0x43, 0x55, 0x49, 0x54,
	0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12,
	0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4d, 0x50, 0x49, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41,
	0x4c, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x05,
	0x32, 0x80, 0x01, 0x0a, 0x05, 0x50, 0x6f, 0x6c, 0x61, 0x72, 0x12, 0x35, 0x0a, 0x0e, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x73, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x12, 0x0e, 0x2e, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x40, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x73, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x70, 0x6f, 0x6c, 0x61, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x28, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x6e, 0x65, 0x63, 0x72, 0x6f, 0x6e, 0x2e, 0x64, 0x65,
	0x76, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x41, 0x72, 0x63, 0x74, 0x69, 0x63, 0x4f, 0x4a, 0x2f, 0x70,
	0x6f, 0x6c, 0x61, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_polar_proto_rawDescOnce sync.Once
	file_polar_proto_rawDescData = file_polar_proto_rawDesc
)

func file_polar_proto_rawDescGZIP() []byte {
	file_polar_proto_rawDescOnce.Do(func() {
		file_polar_proto_rawDescData = protoimpl.X.CompressGZIP(file_polar_proto_rawDescData)
	})
	return file_polar_proto_rawDescData
}

var file_polar_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_polar_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_polar_proto_goTypes = []interface{}{
	(CaseVerdict)(0),                 // 0: polar.CaseVerdict
	(FinalVerdict)(0),                // 1: polar.FinalVerdict
	(Submission_Constraints_Flag)(0), // 2: polar.Submission.Constraints.Flag
	(Request_Type)(0),                // 3: polar.Request.Type
	(*CaseResult)(nil),               // 4: polar.CaseResult
	(*FinalResult)(nil),              // 5: polar.FinalResult
	(*Result)(nil),                   // 6: polar.Result
	(*Judge)(nil),                    // 7: polar.Judge
	(*RuntimeDefinition)(nil),        // 8: polar.RuntimeDefinition
	(*Submission)(nil),               // 9: polar.Submission
	(*Request)(nil),                  // 10: polar.Request
	(*HandshakeData)(nil),            // 11: polar.HandshakeData
	(*Response)(nil),                 // 12: polar.Response
	(*Judge_Runtime)(nil),            // 13: polar.Judge.Runtime
	(*Submission_Constraints)(nil),   // 14: polar.Submission.Constraints
	(*emptypb.Empty)(nil),            // 15: google.protobuf.Empty
	(*anypb.Any)(nil),                // 16: google.protobuf.Any
	(*wrapperspb.BoolValue)(nil),     // 17: google.protobuf.BoolValue
}
var file_polar_proto_depIdxs = []int32{
	0,  // 0: polar.CaseResult.verdict:type_name -> polar.CaseVerdict
	0,  // 1: polar.FinalResult.lastNonAcVerdict:type_name -> polar.CaseVerdict
	1,  // 2: polar.FinalResult.verdict:type_name -> polar.FinalVerdict
	4,  // 3: polar.Result.case:type_name -> polar.CaseResult
	5,  // 4: polar.Result.final:type_name -> polar.FinalResult
	15, // 5: polar.Result.none:type_name -> google.protobuf.Empty
	13, // 6: polar.Judge.runtimes:type_name -> polar.Judge.Runtime
	14, // 7: polar.Submission.constraints:type_name -> polar.Submission.Constraints
	3,  // 8: polar.Request.type:type_name -> polar.Request.Type
	16, // 9: polar.Request.data:type_name -> google.protobuf.Any
	8,  // 10: polar.HandshakeData.runtimes:type_name -> polar.RuntimeDefinition
	11, // 11: polar.Response.handshakeData:type_name -> polar.HandshakeData
	9,  // 12: polar.Response.submission:type_name -> polar.Submission
	15, // 13: polar.Response._:type_name -> google.protobuf.Empty
	10, // 14: polar.Polar.ConnectAsJudge:input_type -> polar.Request
	6,  // 15: polar.Polar.ConnectAsProducer:input_type -> polar.Result
	12, // 16: polar.Polar.ConnectAsJudge:output_type -> polar.Response
	17, // 17: polar.Polar.ConnectAsProducer:output_type -> google.protobuf.BoolValue
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_polar_proto_init() }
func file_polar_proto_init() {
	if File_polar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_polar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Judge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Submission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Judge_Runtime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polar_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Submission_Constraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_polar_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Result_Case)(nil),
		(*Result_Final)(nil),
		(*Result_None)(nil),
	}
	file_polar_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Response_HandshakeData)(nil),
		(*Response_Submission)(nil),
		(*Response_X)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_polar_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_polar_proto_goTypes,
		DependencyIndexes: file_polar_proto_depIdxs,
		EnumInfos:         file_polar_proto_enumTypes,
		MessageInfos:      file_polar_proto_msgTypes,
	}.Build()
	File_polar_proto = out.File
	file_polar_proto_rawDesc = nil
	file_polar_proto_goTypes = nil
	file_polar_proto_depIdxs = nil
}
