// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.33
// source: polar.proto

package pb

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_polar_proto struct{}

func (drpcEncoding_File_polar_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_polar_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_polar_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_polar_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_polar_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCPolarClient interface {
	DRPCConn() drpc.Conn

	ConnectAsJudge(ctx context.Context) (DRPCPolar_ConnectAsJudgeClient, error)
	ConnectAsProducer(ctx context.Context) (DRPCPolar_ConnectAsProducerClient, error)
}

type drpcPolarClient struct {
	cc drpc.Conn
}

func NewDRPCPolarClient(cc drpc.Conn) DRPCPolarClient {
	return &drpcPolarClient{cc}
}

func (c *drpcPolarClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcPolarClient) ConnectAsJudge(ctx context.Context) (DRPCPolar_ConnectAsJudgeClient, error) {
	stream, err := c.cc.NewStream(ctx, "/polar.Polar/ConnectAsJudge", drpcEncoding_File_polar_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcPolar_ConnectAsJudgeClient{stream}
	return x, nil
}

type DRPCPolar_ConnectAsJudgeClient interface {
	drpc.Stream
	Send(*Request) error
	Recv() (*Response, error)
}

type drpcPolar_ConnectAsJudgeClient struct {
	drpc.Stream
}

func (x *drpcPolar_ConnectAsJudgeClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcPolar_ConnectAsJudgeClient) Send(m *Request) error {
	return x.MsgSend(m, drpcEncoding_File_polar_proto{})
}

func (x *drpcPolar_ConnectAsJudgeClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.MsgRecv(m, drpcEncoding_File_polar_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcPolar_ConnectAsJudgeClient) RecvMsg(m *Response) error {
	return x.MsgRecv(m, drpcEncoding_File_polar_proto{})
}

func (c *drpcPolarClient) ConnectAsProducer(ctx context.Context) (DRPCPolar_ConnectAsProducerClient, error) {
	stream, err := c.cc.NewStream(ctx, "/polar.Polar/ConnectAsProducer", drpcEncoding_File_polar_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcPolar_ConnectAsProducerClient{stream}
	return x, nil
}

type DRPCPolar_ConnectAsProducerClient interface {
	drpc.Stream
	Send(*Result) error
	CloseAndRecv() (*wrapperspb.BoolValue, error)
}

type drpcPolar_ConnectAsProducerClient struct {
	drpc.Stream
}

func (x *drpcPolar_ConnectAsProducerClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcPolar_ConnectAsProducerClient) Send(m *Result) error {
	return x.MsgSend(m, drpcEncoding_File_polar_proto{})
}

func (x *drpcPolar_ConnectAsProducerClient) CloseAndRecv() (*wrapperspb.BoolValue, error) {
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrapperspb.BoolValue)
	if err := x.MsgRecv(m, drpcEncoding_File_polar_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcPolar_ConnectAsProducerClient) CloseAndRecvMsg(m *wrapperspb.BoolValue) error {
	if err := x.CloseSend(); err != nil {
		return err
	}
	return x.MsgRecv(m, drpcEncoding_File_polar_proto{})
}

type DRPCPolarServer interface {
	ConnectAsJudge(DRPCPolar_ConnectAsJudgeStream) error
	ConnectAsProducer(DRPCPolar_ConnectAsProducerStream) error
}

type DRPCPolarUnimplementedServer struct{}

func (s *DRPCPolarUnimplementedServer) ConnectAsJudge(DRPCPolar_ConnectAsJudgeStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

func (s *DRPCPolarUnimplementedServer) ConnectAsProducer(DRPCPolar_ConnectAsProducerStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCPolarDescription struct{}

func (DRPCPolarDescription) NumMethods() int { return 2 }

func (DRPCPolarDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/polar.Polar/ConnectAsJudge", drpcEncoding_File_polar_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCPolarServer).
					ConnectAsJudge(
						&drpcPolar_ConnectAsJudgeStream{in1.(drpc.Stream)},
					)
			}, DRPCPolarServer.ConnectAsJudge, true
	case 1:
		return "/polar.Polar/ConnectAsProducer", drpcEncoding_File_polar_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCPolarServer).
					ConnectAsProducer(
						&drpcPolar_ConnectAsProducerStream{in1.(drpc.Stream)},
					)
			}, DRPCPolarServer.ConnectAsProducer, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterPolar(mux drpc.Mux, impl DRPCPolarServer) error {
	return mux.Register(impl, DRPCPolarDescription{})
}

type DRPCPolar_ConnectAsJudgeStream interface {
	drpc.Stream
	Send(*Response) error
	Recv() (*Request, error)
}

type drpcPolar_ConnectAsJudgeStream struct {
	drpc.Stream
}

func (x *drpcPolar_ConnectAsJudgeStream) Send(m *Response) error {
	return x.MsgSend(m, drpcEncoding_File_polar_proto{})
}

func (x *drpcPolar_ConnectAsJudgeStream) Recv() (*Request, error) {
	m := new(Request)
	if err := x.MsgRecv(m, drpcEncoding_File_polar_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcPolar_ConnectAsJudgeStream) RecvMsg(m *Request) error {
	return x.MsgRecv(m, drpcEncoding_File_polar_proto{})
}

type DRPCPolar_ConnectAsProducerStream interface {
	drpc.Stream
	SendAndClose(*wrapperspb.BoolValue) error
	Recv() (*Result, error)
}

type drpcPolar_ConnectAsProducerStream struct {
	drpc.Stream
}

func (x *drpcPolar_ConnectAsProducerStream) SendAndClose(m *wrapperspb.BoolValue) error {
	if err := x.MsgSend(m, drpcEncoding_File_polar_proto{}); err != nil {
		return err
	}
	return x.CloseSend()
}

func (x *drpcPolar_ConnectAsProducerStream) Recv() (*Result, error) {
	m := new(Result)
	if err := x.MsgRecv(m, drpcEncoding_File_polar_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcPolar_ConnectAsProducerStream) RecvMsg(m *Result) error {
	return x.MsgRecv(m, drpcEncoding_File_polar_proto{})
}
